name: Linting, testing, building
on:
  push:
    branches: [master, develop]
  pull_request:
    branches: [master, develop]
jobs:
  pipline:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [17.x]

    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js environment
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install node_modules
        run: npm install

      - name: Build production project
        run: npm run build:prod
        if: always()

      - name: Linting typescript
        run: npm run lint:ts
        if: always()

      - name: Linting css
        run: npm run lint:scss
        if: always()

      - name: Unit testing
        run: npm run test:unit
        if: always()

      - name: Storybook build
        run: storybook:build
        if: always()

      - name: UI testing
        run: npm run test:ui:ci
        if: always()
